

CREATE TABLE  IF NOT EXISTS MYDB.CAR 
   (	CARID VARCHAR(500), 
	NAME VARCHAR(500), 
	SEATER VARCHAR(500), 
	QUANTITY INT, 
	ISSUED INT, 
	 CONSTRAINT CAR_PK PRIMARY KEY (CARID)
   )
;



CREATE TABLE  IF NOT EXISTS MYDB.RENTER
   (	ID INT AUTO_INCREMENT, 
	NAME VARCHAR(500), 
	PASSWORD VARCHAR(500), 
	EMAIL VARCHAR(500), 
	MOBILE BIGINT , 
	 CONSTRAINT RENTER_PK PRIMARY KEY (ID)
   )
;




CREATE TABLE  IF NOT EXISTS MYDB.ISSUECAR 
   (	CARID VARCHAR(500) NOT NULL, 
	RENTERID VARCHAR(500) NOT NULL, 
	RENTERNAME VARCHAR(500), 
	RENTERMOBILE INT, 
	ISSUEDDATE DATE, 
	RETURNSTATUS VARCHAR(500)
   )
;